python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-1.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-2.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-3.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-4.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-5.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-6.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-7.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-8.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-9.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-10.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-11.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-12.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-13.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-14.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-15.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-16.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-17.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-18.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-19.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-20.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-21.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-22.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-23.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-24.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-25.csv -read_as fp32 -new_precision 4
python3 ./reduce_precision.py -file weights_and_biases/epoch-0/ev-table/ev-table-26.csv -read_as fp32 -new_precision 4
